import { useState } from 'react';
import { Booking, BookingStatus } from '../types';
import { useCompanySettings } from '../contexts/CompanySettingsContext';
import { 
  X, Printer, Download, FileText, Calendar, Users, 
  DollarSign, CheckCircle2, Building2, MapPin, 
  ShieldCheck, ArrowRight, Tag, Filter, Clock
} from 'lucide-react';
import { sounds } from '../utils/sounds';

interface BookingsReportModalProps {
  bookings: Booking[];
  allBookings: Booking[];
  activeFilters: {
    search: string;
    status: BookingStatus | 'ALL';
    clientType: string;
    datePreset: string;
    dateFrom: string;
    dateTo: string;
  };
  currentUser: {
    name: string;
    role: string;
    email?: string;
  } | null;
  onClose: () => void;
}

export default function BookingsReportModal({
  bookings: initialFilteredBookings,
  allBookings,
  activeFilters,
  currentUser,
  onClose,
}: BookingsReportModalProps) {
  const { settings } = useCompanySettings();
  const [scope, setScope] = useState<'FILTERED' | 'ALL'>('FILTERED');
  
  const rawList = scope === 'FILTERED' ? initialFilteredBookings : allBookings;
  const currentList = Array.isArray(rawList) ? rawList : [];

  // Financial aggregates
  const totalAgreed = currentList.reduce((s, b) => s + (Number.isFinite(Number(b.totalAgreedAmount)) ? Number(b.totalAgreedAmount) : 0), 0);
  const totalAdvance = currentList.reduce((s, b) => s + (Number.isFinite(Number(b.advanceReceived)) ? Number(b.advanceReceived) : 0), 0);
  const totalBalance = Math.max(0, totalAgreed - totalAdvance);
  const totalPax = currentList.reduce((s, b) => s + (Number.isFinite(Number(b.paxCount)) ? Number(b.paxCount) : 0), 0);

  // Status breakdown
  const statusCounts = currentList.reduce((acc, b) => {
    acc[b.status] = (acc[b.status] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  // Generated timestamp
  const reportDate = new Date();
  const formattedDate = reportDate.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  const formattedTime = reportDate.toLocaleTimeString('en-US', {
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: true,
  });
  const reportId = `REP-BKG-${reportDate.getFullYear()}${String(reportDate.getMonth() + 1).padStart(2, '0')}${String(reportDate.getDate()).padStart(2, '0')}-${Math.floor(1000 + Math.random() * 9000)}`;

  const handlePrint = () => {
    sounds.click();
    window.print();
  };

  const handleExportCSV = () => {
    sounds.click();
    const rows = [
      ['PAILA NEPAL TOURS & TRAVELS PVT. LTD. - BOOKINGS AUDIT REPORT'],
      [`Report Reference: ${reportId}`],
      [`Generated On: ${formattedDate} at ${formattedTime}`],
      [`Generated By: ${currentUser?.name || 'Administrator'} (${currentUser?.role || 'SUPER_ADMIN'})`],
      [`Scope: ${scope === 'FILTERED' ? 'Filtered Criteria' : 'All Database Records'} (${currentList.length} Bookings)`],
      [`Total Pax: ${totalPax}`, `Total Contract Value: NPR ${totalAgreed.toLocaleString()}`, `Total Advance Received: NPR ${totalAdvance.toLocaleString()}`, `Total Balance Due: NPR ${totalBalance.toLocaleString()}`],
      [],
      [
        'S.N.',
        'Booking Code',
        'Client Name',
        'Client Type',
        'Contact Phone',
        'Contact Email',
        'Tour Package',
        'Start Date',
        'End Date',
        'Duration (Days)',
        'Pax Count',
        'Agreed Total (NPR)',
        'Advance Received (NPR)',
        'Balance Due (NPR)',
        'Booking Status',
        'Assigned Tour Operator',
        'Created By',
        'Created Date',
        'Special Notes'
      ]
    ];

    currentList.forEach((b, idx) => {
      let durationDays = 1;
      try {
        const start = new Date(b.startDate).getTime();
        const end = new Date(b.endDate).getTime();
        if (Number.isFinite(start) && Number.isFinite(end) && end >= start) {
          durationDays = Math.max(1, Math.round((end - start) / (1000 * 60 * 60 * 24)) + 1);
        } else {
          durationDays = 1;
        }
      } catch {
        durationDays = 1;
      }

      rows.push([
        String(idx + 1),
        `"${b.bookingCode}"`,
        `"${b.clientName}"`,
        `"${b.clientType}"`,
        `"${b.clientPhone}"`,
        `"${b.clientEmail || ''}"`,
        `"${b.packageName || 'Custom Itinerary'}"`,
        `"${b.startDate}"`,
        `"${b.endDate}"`,
        String(durationDays),
        String(b.paxCount),
        String(b.totalAgreedAmount),
        String(b.advanceReceived),
        String(b.totalAgreedAmount - b.advanceReceived),
        `"${b.status}"`,
        `"${b.assignedTourOperatorName || 'Unassigned'}"`,
        `"${b.createdByName || 'Staff'}"`,
        `"${b.createdAt}"`,
        `"${(b.notes || '').replace(/"/g, '""')}"`
      ]);
    });

    // Summary row
    rows.push([]);
    rows.push([
      'TOTALS',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      String(totalPax),
      String(totalAgreed),
      String(totalAdvance),
      String(totalBalance),
      '',
      '',
      '',
      '',
      ''
    ]);

    const csvContent = '\uFEFF' + rows.map(r => r.join(',')).join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.setAttribute('href', url);
    link.setAttribute('download', `Paila-Nepal-Bookings-Report-${reportDate.toISOString().slice(0, 10)}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const getStatusBadge = (status: BookingStatus) => {
    switch (status) {
      case 'PROPOSED':
        return 'bg-amber-100 text-amber-800 border-amber-200';
      case 'CONFIRMED':
        return 'bg-blue-100 text-blue-800 border-blue-200';
      case 'IN_PROGRESS':
        return 'bg-emerald-100 text-emerald-800 border-emerald-200';
      case 'COMPLETED':
        return 'bg-slate-100 text-slate-800 border-slate-200';
      case 'CANCELLED':
        return 'bg-rose-100 text-rose-800 border-rose-200';
    }
  };

  return (
    <div className="fixed inset-0 bg-slate-900/75 backdrop-blur-xs z-50 flex items-start justify-center overflow-y-auto p-2 sm:p-4 no-print-bg">
      <div className="bg-white w-full max-w-5xl my-4 sm:my-6 rounded-2xl shadow-2xl overflow-hidden border border-slate-200 animate-fade-in print:max-w-none print:m-0 print:border-none print:shadow-none">
        
        {/* Controls Bar (Hidden during Print) */}
        <div className="bg-slate-900 text-white px-5 py-3.5 flex flex-wrap items-center justify-between gap-3 no-print sticky top-0 z-20 shadow-md">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg bg-paila-orange flex items-center justify-center text-white">
              <FileText size={18} />
            </div>
            <div>
              <h2 className="text-sm font-bold text-white flex items-center gap-2">
                <span>Bookings Accounting & Archival Report</span>
                <span className="text-[10px] bg-blue-500/20 text-blue-300 px-2 py-0.5 rounded-full font-mono border border-blue-500/30">
                  {reportId}
                </span>
              </h2>
              <p className="text-xs text-slate-400">
                Official statement view for offline archival, tax reporting, and audit verification
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2.5 flex-wrap">
            {/* Scope Switcher */}
            <div className="flex items-center bg-slate-800 p-1 rounded-xl border border-slate-700 text-xs">
              <button
                type="button"
                onClick={() => setScope('FILTERED')}
                className={`px-3 py-1 rounded-lg font-medium transition-all ${
                  scope === 'FILTERED'
                    ? 'bg-paila-blue text-white shadow-sm font-semibold'
                    : 'text-slate-400 hover:text-white'
                }`}
              >
                Filtered ({initialFilteredBookings?.length || 0})
              </button>
              <button
                type="button"
                onClick={() => setScope('ALL')}
                className={`px-3 py-1 rounded-lg font-medium transition-all ${
                  scope === 'ALL'
                    ? 'bg-paila-blue text-white shadow-sm font-semibold'
                    : 'text-slate-400 hover:text-white'
                }`}
              >
                All Bookings ({allBookings?.length || 0})
              </button>
            </div>

            {/* CSV Download */}
            <button
              onClick={handleExportCSV}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 hover:text-white border border-slate-700 rounded-xl text-xs font-semibold transition-all cursor-pointer"
              title="Download CSV Spreadsheet"
            >
              <Download size={14} />
              <span>Export CSV</span>
            </button>

            {/* Print / PDF Button */}
            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-4 py-1.5 bg-gradient-to-r from-paila-orange to-orange-600 hover:from-orange-600 hover:to-orange-700 text-white rounded-xl text-xs font-bold shadow-md hover:shadow-lg transition-all cursor-pointer"
              title="Print or Save as PDF"
            >
              <Printer size={14} />
              <span>Print / Save PDF</span>
            </button>

            {/* Close Button */}
            <button
              onClick={() => {
                sounds.modalClose();
                onClose();
              }}
              className="p-1.5 hover:bg-white/10 rounded-xl text-slate-400 hover:text-white transition-colors cursor-pointer"
              title="Close report"
            >
              <X size={18} />
            </button>
          </div>
        </div>

        {/* Printable Document Container */}
        <div className="print-container bg-white p-6 sm:p-10 text-slate-800 font-sans">
          
          {/* Header & Letterhead */}
          <div className="border-b-2 border-paila-blue pb-5 mb-6">
            <div className="flex items-start justify-between">
              <div className="flex items-center gap-3.5">
                <div className="w-16 h-16 bg-paila-blue rounded-2xl flex items-center justify-center text-white font-black text-xl shadow-md border-2 border-blue-900 shrink-0">
                  {(settings?.companyName || 'Paila Nepal').split(' ').filter(Boolean).slice(0, 2).map(w => w[0]?.toUpperCase()).join('') || 'PN'}
                </div>
                <div>
                  <h1 className="text-2xl font-black text-paila-blue tracking-tight leading-tight uppercase">
                    {settings.companyName}
                  </h1>
                  <p className="text-xs font-semibold text-paila-orange uppercase tracking-wider mt-0.5">
                    {settings.tagline || 'Trekking • Mountaineering • Institutional Excursions • Luxury Tours'}
                  </p>
                  <p className="text-[11px] text-slate-500 mt-1">
                    Government Registered Travel & Tour Operator • Reg: {settings.registrationNumber || '2841/078'}
                  </p>
                </div>
              </div>

              <div className="text-right text-[11px] text-slate-600 leading-relaxed shrink-0">
                <p className="font-bold text-slate-900 text-xs">Corporate & Accounts Office</p>
                <p>{settings.address}</p>
                <p>Phone: {settings.phone}</p>
                <p>Email: {settings.email || `accounts@${settings.domain}`} • {settings.domain}</p>
                <p className="font-mono text-slate-800 mt-0.5">
                  <strong>PAN:</strong> {settings.panNumber} &nbsp;|&nbsp; <strong>VAT:</strong> {settings.vatNumber}
                </p>
              </div>
            </div>
          </div>

          {/* Report Statement Title & Metadata Bar */}
          <div className="bg-slate-50 border border-slate-200 rounded-xl p-4 mb-6">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-3 border-b border-slate-200/80 mb-3">
              <div>
                <span className="text-[10px] font-bold uppercase tracking-widest text-paila-blue bg-blue-100/70 px-2 py-0.5 rounded">
                  Official Audit Statement
                </span>
                <h2 className="text-lg font-bold text-slate-900 mt-1">
                  Bookings Financial & Operations Summary Report
                </h2>
              </div>
              <div className="text-right text-xs">
                <span className="text-slate-500">Report Ref:</span>{' '}
                <span className="font-mono font-bold text-slate-900">{reportId}</span>
              </div>
            </div>

            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs">
              <div>
                <span className="text-slate-500 block text-[11px]">Generated Date & Time:</span>
                <span className="font-semibold text-slate-800">{formattedDate}, {formattedTime}</span>
              </div>
              <div>
                <span className="text-slate-500 block text-[11px]">Authorized Signatory / User:</span>
                <span className="font-semibold text-slate-800">{currentUser?.name || 'Administrator'}</span>
                <span className="text-slate-500 text-[10px] block">({currentUser?.role || 'SUPER_ADMIN'})</span>
              </div>
              <div>
                <span className="text-slate-500 block text-[11px]">Report Dataset Scope:</span>
                <span className="font-semibold text-paila-blue">
                  {scope === 'FILTERED' ? 'Filtered Selection' : 'Full Complete Database'} ({currentList.length} Bookings)
                </span>
              </div>
              <div>
                <span className="text-slate-500 block text-[11px]">Applied Filter Criteria:</span>
                <span className="font-medium text-slate-700">
                  {scope === 'FILTERED' ? (
                    <>
                      {activeFilters?.status && activeFilters.status !== 'ALL' && `Status: ${activeFilters.status} • `}
                      {activeFilters?.clientType && activeFilters.clientType !== 'ALL' && `Type: ${activeFilters.clientType} • `}
                      {activeFilters?.dateFrom && `From: ${activeFilters.dateFrom} `}
                      {activeFilters?.dateTo && `To: ${activeFilters.dateTo} `}
                      {activeFilters?.search && `Query: "${activeFilters.search}"`}
                      {(!activeFilters || (activeFilters.status === 'ALL' && activeFilters.clientType === 'ALL' && !activeFilters.dateFrom && !activeFilters.dateTo && !activeFilters.search)) && 'All Criteria'}
                    </>
                  ) : (
                    'Unfiltered (All Records)'
                  )}
                </span>
              </div>
            </div>
          </div>

          {/* Key Financial & Operational Summary Tiles */}
          <div className="grid grid-cols-2 sm:grid-cols-5 gap-3 mb-6">
            <div className="bg-slate-50 border border-slate-200 rounded-xl p-3 text-center">
              <span className="text-[10px] font-bold text-slate-500 uppercase tracking-wider block">Total Bookings</span>
              <span className="text-xl font-black text-slate-900 mt-1 block">{currentList.length}</span>
              <span className="text-[10px] text-slate-500 mt-0.5 block">Dossiers</span>
            </div>
            <div className="bg-slate-50 border border-slate-200 rounded-xl p-3 text-center">
              <span className="text-[10px] font-bold text-slate-500 uppercase tracking-wider block">Total Travelers</span>
              <span className="text-xl font-black text-paila-blue mt-1 block">{Number.isFinite(totalPax) ? totalPax : 0}</span>
              <span className="text-[10px] text-slate-500 mt-0.5 block">Total Pax</span>
            </div>
            <div className="bg-blue-50/70 border border-blue-200 rounded-xl p-3 text-center">
              <span className="text-[10px] font-bold text-blue-800 uppercase tracking-wider block">Gross Contract Value</span>
              <span className="text-xl font-black text-blue-900 mt-1 block">NPR {totalAgreed.toLocaleString()}</span>
              <span className="text-[10px] text-blue-700 mt-0.5 block">100% Agreed Total</span>
            </div>
            <div className="bg-emerald-50/70 border border-emerald-200 rounded-xl p-3 text-center">
              <span className="text-[10px] font-bold text-emerald-800 uppercase tracking-wider block">Advances Received</span>
              <span className="text-xl font-black text-emerald-700 mt-1 block">NPR {totalAdvance.toLocaleString()}</span>
              <span className="text-[10px] text-emerald-700 mt-0.5 block">
                {totalAgreed > 0 ? `${Math.round((totalAdvance / totalAgreed) * 100)}% Collected` : '0%'}
              </span>
            </div>
            <div className="bg-amber-50/70 border border-amber-200 rounded-xl p-3 text-center col-span-2 sm:col-span-1">
              <span className="text-[10px] font-bold text-amber-800 uppercase tracking-wider block">Outstanding Balance</span>
              <span className="text-xl font-black text-amber-900 mt-1 block">NPR {totalBalance.toLocaleString()}</span>
              <span className="text-[10px] text-amber-700 mt-0.5 block">Receivable</span>
            </div>
          </div>

          {/* Status Breakdown Summary Chips */}
          <div className="flex flex-wrap items-center gap-2 mb-6 pb-4 border-b border-slate-100 text-xs">
            <span className="text-slate-500 font-semibold">Status Distribution:</span>
            {['PROPOSED', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'].map(st => {
              const count = statusCounts[st] || 0;
              if (count === 0) return null;
              return (
                <span
                  key={st}
                  className={`px-2.5 py-0.5 rounded-lg border font-semibold text-xs ${getStatusBadge(st as BookingStatus)}`}
                >
                  {st.replace('_', ' ')}: <strong>{Number.isFinite(count) ? count : 0}</strong>
                </span>
              );
            })}
          </div>

          {/* Bookings Tabular Ledger */}
          <div className="mb-6 overflow-x-auto">
            <table className="w-full text-left text-xs border-collapse border border-slate-200">
              <thead>
                <tr className="bg-slate-100 text-slate-700 font-bold border-b border-slate-200 uppercase text-[10px] tracking-wider">
                  <th className="p-2.5 border border-slate-200 w-8 text-center">#</th>
                  <th className="p-2.5 border border-slate-200">Booking Ref</th>
                  <th className="p-2.5 border border-slate-200">Client / Institution</th>
                  <th className="p-2.5 border border-slate-200">Tour Package</th>
                  <th className="p-2.5 border border-slate-200">Travel Window</th>
                  <th className="p-2.5 border border-slate-200 text-center">Pax</th>
                  <th className="p-2.5 border border-slate-200 text-right">Agreed (NPR)</th>
                  <th className="p-2.5 border border-slate-200 text-right">Advance (NPR)</th>
                  <th className="p-2.5 border border-slate-200 text-right">Balance (NPR)</th>
                  <th className="p-2.5 border border-slate-200 text-center">Status</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-200">
                {currentList.map((b, idx) => {
                  const total = Number.isFinite(Number(b.totalAgreedAmount)) ? Number(b.totalAgreedAmount) : 0;
                  const advance = Number.isFinite(Number(b.advanceReceived)) ? Number(b.advanceReceived) : 0;
                  const balance = Math.max(0, total - advance);
                  return (
                    <tr key={b.id} className={idx % 2 === 0 ? 'bg-white' : 'bg-slate-50/50'}>
                      <td className="p-2.5 border border-slate-200 text-center font-mono text-slate-500">
                        {idx + 1}
                      </td>
                      <td className="p-2.5 border border-slate-200 font-mono font-bold text-paila-blue whitespace-nowrap">
                        {b.bookingCode}
                      </td>
                      <td className="p-2.5 border border-slate-200">
                        <div className="font-bold text-slate-900">{b.clientName}</div>
                        <div className="text-[10px] text-slate-500">
                          {b.clientType} • {b.clientPhone}
                        </div>
                      </td>
                      <td className="p-2.5 border border-slate-200">
                        <div className="font-medium text-slate-800">{b.packageName || 'Custom Itinerary'}</div>
                        {b.assignedTourOperatorName && (
                          <div className="text-[10px] text-slate-500">Leader: {b.assignedTourOperatorName}</div>
                        )}
                      </td>
                      <td className="p-2.5 border border-slate-200 text-slate-700 whitespace-nowrap text-[11px]">
                        <div>{b.startDate}</div>
                        <div className="text-slate-400 text-[10px]">to {b.endDate}</div>
                      </td>
                      <td className="p-2.5 border border-slate-200 text-center font-bold text-slate-800">
                        {Number.isFinite(Number(b.paxCount)) ? b.paxCount : 1}
                      </td>
                      <td className="p-2.5 border border-slate-200 text-right font-mono font-medium text-slate-900 whitespace-nowrap">
                        {total.toLocaleString()}
                      </td>
                      <td className="p-2.5 border border-slate-200 text-right font-mono font-medium text-emerald-700 whitespace-nowrap">
                        {advance.toLocaleString()}
                      </td>
                      <td className="p-2.5 border border-slate-200 text-right font-mono font-medium text-amber-800 whitespace-nowrap">
                        {balance.toLocaleString()}
                      </td>
                      <td className="p-2.5 border border-slate-200 text-center whitespace-nowrap">
                        <span className={`px-2 py-0.5 rounded text-[10px] font-bold border ${getStatusBadge(b.status)}`}>
                          {b.status.replace('_', ' ')}
                        </span>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
              <tfoot>
                <tr className="bg-slate-100 font-bold text-slate-900 border-t-2 border-slate-300">
                  <td colSpan={5} className="p-2.5 border border-slate-200 text-right uppercase tracking-wider text-[11px]">
                    Grand Totals ({currentList.length} Bookings):
                  </td>
                  <td className="p-2.5 border border-slate-200 text-center font-bold text-paila-blue">
                    {Number.isFinite(totalPax) ? totalPax : 0}
                  </td>
                  <td className="p-2.5 border border-slate-200 text-right font-mono text-paila-blue">
                    NPR {totalAgreed.toLocaleString()}
                  </td>
                  <td className="p-2.5 border border-slate-200 text-right font-mono text-emerald-700">
                    NPR {totalAdvance.toLocaleString()}
                  </td>
                  <td className="p-2.5 border border-slate-200 text-right font-mono text-amber-900">
                    NPR {totalBalance.toLocaleString()}
                  </td>
                  <td className="p-2.5 border border-slate-200"></td>
                </tr>
              </tfoot>
            </table>
          </div>

          {/* Audit Declaration & Official Sign-off Block */}
          <div className="mt-8 pt-4 border-t border-slate-200 avoid-break">
            <p className="text-[10px] text-slate-500 italic mb-6 leading-relaxed">
              Certification: This document serves as an authentic financial & operations ledger statement extracted directly from the Paila Nepal Holiday ERP Database. All advance payment entries and outstanding contracts are certified correct and valid for offline tax reconciliation, audit filing, and institutional archival.
            </p>

            <div className="grid grid-cols-3 gap-6 pt-4 text-center text-xs">
              <div className="border-t border-slate-300 pt-2">
                <p className="font-bold text-slate-900">{currentUser?.name || 'Administrator'}</p>
                <p className="text-[10px] text-slate-500">{currentUser?.role || 'OPERATIONS'} / Prepared By</p>
                <p className="text-[9px] text-slate-400 mt-1">Signature & Date</p>
              </div>

              <div className="border-t border-slate-300 pt-2">
                <p className="font-bold text-slate-900">Finance & Accounts Officer</p>
                <p className="text-[10px] text-slate-500">Accounts Department / Verified By</p>
                <p className="text-[9px] text-slate-400 mt-1">Signature & Date</p>
              </div>

              <div className="border-t border-slate-300 pt-2">
                <p className="font-bold text-slate-900">Managing Director</p>
                <p className="text-[10px] text-slate-500">{settings.companyName} / Authorized Signatory</p>
                <p className="text-[9px] text-slate-400 mt-1">Official Company Seal</p>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  );
}
